### ISSUE TITLE
add sections: NLP, Graphs, Cheminformatics, Software Engineering

### ISSUE THREAD

**Issue by mlederbauer** [mlederbauer/awesome-learning-digital-chemistry#2]
or add as a tag?

**Comment by kjappelbaum** [comment]
do you want to link to learning material in general or do you want to have everything a link to chemistry/materials science?

For general resources: 
- https://github.com/karpathy/nn-zero-to-hero for neural networks basics and NLP 
- https://github.com/the-turing-way/the-turing-way for data management/reproducible science


Programming for chemists: 
- https://weisscharlesj.github.io/SciCompforChemists/notebooks/introduction/intro.html
- https://github.com/MolSSI-Education/python_scripting_cms

Basics of cheminformatics: https://github.com/Sulstice/Cheminformatics-Teaching-Material

Basics of ML and materials informatics: 
- https://github.com/sp8rks/MaterialsInformatics
- https://github.com/aronwalsh/MLforMaterials

Self-driving labs: https://github.com/sparks-baird/self-driving-lab-demo

A related awesome list: https://github.com/kevingreenman/awesome-chemical-engineering-education

And: very sorry for being late with the additions (I still say yes to too many things ;)) :/

**Comment by mlederbauer** [comment]
Hi Kevin @kjappelbaum  – many thanks for your contributions and no worries about the commitment! This is a growing list and every time that your have an idea or addition in the future, feel free to get in touch or open a PR.

Regarding the topic of the list, that’s a great point — while I would keep it “chemistry/matsci” focused, adding some basics as well would be great — similar to the NN zero to hero you mentioned.

I’ll incorporate your additions in a sepatate PR and restructure the resources accordingly!

Best,
Magdalena
